import type { Metadata } from "next";
// import { Inter } from "next/font/google"
import { Poppins } from "next/font/google"
import "./globals.css";
import Modal from "./_components/Modal";
import { ModalProvider } from "./_context/ModalContext";

const poppins = Poppins({ weight: ["100", "200", "500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "flowtie.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ModalProvider>
          {children}
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
}
